; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Aker LQ"
#define MyAppVersion "0.0"
#define MyAppPublisher "Gaby .inc"
#define MyAppExeName "Liquidaciones.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{052E07A0-0A39-4DFE-B311-8356EB95BCE4}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DisableDirPage=yes
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Users\Gabriel\Desktop\instalador LQ
OutputBaseFilename=Aker LQ
SetupIconFile=D:\Downloads\rat.ico
SolidCompression=yes
WizardStyle=classic dynamic

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\BLL.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\BLL.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\DAL.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\DAL.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Liquidaciones.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Liquidaciones.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Liquidaciones.dll.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Liquidaciones.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Liquidaciones.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Liquidaciones.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.Configuration.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.Configuration.Binder.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.Configuration.CommandLine.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.Configuration.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.Configuration.EnvironmentVariables.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.Configuration.FileExtensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.Configuration.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.Configuration.UserSecrets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.DependencyInjection.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.DependencyInjection.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.FileProviders.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.FileProviders.Physical.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.FileSystemGlobbing.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.Hosting.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.Hosting.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.Logging.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.Logging.Configuration.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.Logging.Console.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.Logging.Debug.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.Logging.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.Logging.EventLog.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.Logging.EventSource.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.Options.ConfigurationExtensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.Options.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\Microsoft.Extensions.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\WinForms.DataVisualization.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Gabriel\repositories\cliente_liquidaciones\UI\bin\Debug\net6.0-windows\WinForms.DataVisualization.Utilities.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

